### ISSUE TITLE
Cannot run sbt test twice

### ISSUE THREAD

**Issue by valencik** [shadaj/scalapy#37] opened 2019-09-26 01:31 UTC
On current master, and at least the commit before it I cannot run the following shell command `sbt clean test && sbt test` without getting a linking error:

```
[info] Compiling to native code (1020 ms)
[info] Linking native code (immix gc) (184 ms)
[error] java.nio.file.ClosedFileSystemException
[error]         at com.sun.nio.zipfs.ZipFileSystem.ensureOpen(ZipFileSystem.java:1084)
[error]         at com.sun.nio.zipfs.ZipFileSystem.newByteChannel(ZipFileSystem.java:633)
[error]         at com.sun.nio.zipfs.ZipPath.newByteChannel(ZipPath.java:739)
[error]         at com.sun.nio.zipfs.ZipFileSystemProvider.newByteChannel(ZipFileSystemProvider.java:255)
[error]         at java.nio.file.Files.newByteChannel(Files.java:361)
[error]         at java.nio.file.Files.newByteChannel(Files.java:407)
[error]         at java.nio.file.Files.readAllBytes(Files.java:3152)
[error]         at scala.scalanative.io.VirtualDirectory$NioDirectory.read(VirtualDirectory.scala:72)
```

In other words, running `test` appears to produce target files that make the next run of `test` fail.
Running `sbt clean` or manually removing `core/native/target/scala-2.11/classes` will make the next run of `test` complete successfully.

I believe this is the issue I'm encountering in https://github.com/shadaj/scalapy/pull/35 and encountered in https://github.com/shadaj/scalapy/pull/36. As I think TravisCi caches per branch:
> There is one cache per branch and language version/ compiler version/ JDK version/ Gemfile location/ etc.
(from https://docs.travis-ci.com/user/caching/)

**Comment by shadaj** [comment] 2019-09-27 07:01
/cc @densh, this may be a Scala Native bug. Don't think this is a ScalaPy bug since we're not doing anything special with how linking runs.

@valencik have you seen this with Scala Native 0.4.0-M2? Maybe this is just a bug with the 0.3.x series, which is what's used on master right now.

**Comment by bfdes** [comment] 2019-11-17 14:09
I find that re-runs work when I remove the test `"Can use with statement with file object"` in `MethodCallingTest`, if that helps narrowing down the cause.

**Comment by shadaj** [comment] 2019-11-18 23:33
@valencik @bfdes what happens if you run `coreNative/test` twice? I haven't seen this during development, but I also don't use the aggregate `test` command so I have a hunch that that might be the source of the problem.

**Comment by bfdes** [comment] 2019-11-19 00:04
Running `coreNative/test` on its own is fine no matter how many times I do it. 

I only noticed this error because I hadn't installed the ScalaNative dependencies until very recently. (Before that I was getting an error associated with missing dependencies.)

**Comment by shadaj** [comment] 2020-11-13 19:17
This seems to be fixed now, I am able to repeatedly run native tests without any failures. Closing for now, but please let me know if this is still an issue!

**Closed by shadaj** 2020-11-13 19:17 UTC
